### ISSUE TITLE
UTXO Selection Strategy

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin-wallet#94]
I feel it's a good time to consider more about the `selection_strategy`, better to have the updated one in `1.1.0` milestone to avoid another incompatibility in the future.

Currently our `selection_strategy` support 2: `all` and `smallest`:
```
        - selection_strategy:
            help: Coin/Output selection strategy.
            short: s
            long: selection
            possible_values:
              - all
              - smallest
            default_value: all
            takes_value: true
```

And current API use a `bool` type for this `selection_strategy`:
```
"selection_strategy_is_use_all": false
```

The explain of this parameter:
- If `all`, attempt to use up as many outputs as possible to create the transaction, up the 'soft limit' of `max_outputs`. This helps to reduce the size of the UTXO set and the amount of data stored in the wallet, and minimizes fees. This will generally result in many inputs and a large change output(s), usually much larger than the amount being sent.
- If `smallest`, the transaction will include as many outputs as are needed to meet the amount, and no more, starting with the ***smallest*** value outputs.

I would propose to add a new one: `biggest`, the meaning of this `biggest` strategy:
- If `biggest`, the transaction will include as many outputs as are needed to meet the amount, and no more, starting with the ***biggest*** value outputs.

The use case is for splitting, in case I want to have more UTXO sets for paying out (for example miners payout in a pool), the better way is to start selection from biggest value outputs, instead of from smallest.

Do you have more `selection_strategy` to be requested in this version? before we give a PR on this feature.
